### ISSUE TITLE
(afputils) certain IIDX BGAs are completely blank

### ISSUE THREAD

**Issue by artConoisseur** [DragonMinded/bemaniutils#67] opened 2022-12-07 23:43 UTC
In certain songs, the `seq_` animations (basically the ones that are scripted to play at certain points) only render completely transparent, 1.24kb images for each frame. As far as I know, I have seen this happen with BLUE STRAGGLER (#20005) and Tokyo Shinwa (#25021). Not all animations are affected, though, as the `seq_` animations for DEATH†ZIGOQ ～怒りの高速爆走野郎～ (#20004) appear to render just fine.

For reference, this is what I used to render out the animations:
`py afputils render -v --path SONG_ID --output overlays/SONG_ID/ANIM/SONG_ID-ANIM.png --background-color 0,0,0,0 --enable-anti-aliasing ..\contents\data\graphic\SONG_ID.ifs`

**Comment by ARCHVILE-DRS** [comment] 2023-01-10 19:30
Not a bug, some songs intentionally leave them blank.

`seq_` animations always take priority over the random (i.e. played upon a random key press) overlays; if a random overlay is still playing when it's time for a `seq_` animation to play, the random overlay will be cut off immediately. 

Sometimes (perhaps due to the sheer complexity of the animation), these animations have to be baked into the base video (see: Smashing Wedge from HEROIC VERSE, #27095). Thus blank `seq_` animations are used to prevent random overlays from appearing on top of the baked animations. So if you want those animations, you'll have to look at the corresponding video file for the song.

**Comment by DragonMinded** [comment] 2023-03-19 20:52
Going to close this as a wont-fix due to the way the format works.

**Closed as completed by DragonMinded** 2023-03-19 20:52 UTC
